/* 
 * Static File Analysis API
 *
 * Use this easy service to understand the characteristics of the file your application or service is interacting with. Allowing you to block malware including those in files previously unseen. Helping you avoid zero day attacks.  SophosLabs Intelix passes each submitted file through an array of granular threat detection analyzers composed  of threat deterministic and machine learning models to derive a threat verdict and an intelligence report. Examples of analysis include:  File genetic similarity intersection machine learning analysis, suspicious file attributes machine learning identification, Deep Anti-Virus scanning, industry detection coverage, and a lot more.  The results are available in JSON format, for easy parsing with any programming language, as well as a visually appealing HTML report, ideal for human reading.  You can read more about [SophosLabs Intelix APIs here](/doc/index.html).  #### Billing  You are billed for getting a report. This might happen in the following ways:  * You request a report by file hash. You are billed if SophosLabs can provide you a report. * You submit a file for analysis. You are billed for the submission (pre-paying for the report). You get a job id for the submission.  NOTE: Requests for a report by job id are not billed when the report is provided, as you have already paid at file submit. 
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SophosLabs.Intellix.Client.SwaggerDateConverter;

namespace SophosLabs.Intellix.Model
{
    /// <summary>
    /// AnalysisErrorReport
    /// </summary>
    [DataContract]
    public partial class AnalysisErrorReport : IEquatable<AnalysisErrorReport>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisErrorReport" /> class.
        /// </summary>
        /// <param name="errorCode">Represents the error which happened.Possible error codes:   * **103**: File extraction from archive failed  * **104**: File type is not supported by the analysis engine  * **105**: Unsuccessful analysis  (required).</param>
        /// <param name="errorMessage">A readable explanation of the error code.  (required).</param>
        public AnalysisErrorReport(int? errorCode = default, string errorMessage = default)
        {
            // to ensure "errorCode" is required (not null)
            if (errorCode == null)
            {
                throw new InvalidDataException("errorCode is a required property for AnalysisErrorReport and cannot be null");
            }
            else
            {
                ErrorCode = errorCode;
            }
            // to ensure "errorMessage" is required (not null)
            if (errorMessage == null)
            {
                throw new InvalidDataException("errorMessage is a required property for AnalysisErrorReport and cannot be null");
            }
            else
            {
                ErrorMessage = errorMessage;
            }
        }

        /// <summary>
        /// Represents the error which happened.Possible error codes:   * **103**: File extraction from archive failed  * **104**: File type is not supported by the analysis engine  * **105**: Unsuccessful analysis 
        /// </summary>
        /// <value>Represents the error which happened.Possible error codes:   * **103**: File extraction from archive failed  * **104**: File type is not supported by the analysis engine  * **105**: Unsuccessful analysis </value>
        [DataMember(Name = "errorCode", EmitDefaultValue = false)]
        public int? ErrorCode { get; set; }

        /// <summary>
        /// A readable explanation of the error code. 
        /// </summary>
        /// <value>A readable explanation of the error code. </value>
        [DataMember(Name = "errorMessage", EmitDefaultValue = false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AnalysisErrorReport {\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AnalysisErrorReport);
        }

        /// <summary>
        /// Returns true if AnalysisErrorReport instances are equal
        /// </summary>
        /// <param name="input">Instance of AnalysisErrorReport to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnalysisErrorReport input)
        {
            if (input == null)
                return false;

            return
                (
                    ErrorCode == input.ErrorCode ||
                    ErrorCode != null &&
                    ErrorCode.Equals(input.ErrorCode)
                ) &&
                (
                    ErrorMessage == input.ErrorMessage ||
                    ErrorMessage != null &&
                    ErrorMessage.Equals(input.ErrorMessage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (ErrorCode != null)
                    hashCode = hashCode * 59 + ErrorCode.GetHashCode();
                if (ErrorMessage != null)
                    hashCode = hashCode * 59 + ErrorMessage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
