/* 
 * API Authentication
 *
 * The SophosLabs Intelix APIs use OAuth2 client credentials (client id and client secret) authentication. The user gets their client credentials during the registration flow. The client credentials contain the following information:  * **Client id:** The unique identifier of the OAuth2 client application. * **Client secret:** The shared secret for the client application.  Example:  * **client id**: 1rqndu80i9dvdl07o34gka06k * **client secret**: 13hvcl1cqj8ne5cg7ee0e7gji6k36k79sr202ja6a5kifg5gte9q  You can read more about [SophosLabs Intelix APIs here](/doc/index.html). 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SophosLabs.Intellix.Client.SwaggerDateConverter;

namespace SophosLabs.Intellix.Model
{
    /// <summary>
    /// ErrorResponseAuth
    /// </summary>
    [DataContract]
        public partial class ErrorResponseAuth :  IEquatable<ErrorResponseAuth>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorResponseAuth" /> class.
        /// </summary>
        public ErrorResponseAuth()
        {
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErrorResponseAuth {\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ErrorResponseAuth);
        }

        /// <summary>
        /// Returns true if ErrorResponseAuth instances are equal
        /// </summary>
        /// <param name="input">Instance of ErrorResponseAuth to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ErrorResponseAuth input)
        {
            if (input == null)
                return false;

            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
