/* 
 * Static File Analysis API
 *
 * Use this easy service to understand the characteristics of the file your application or service is interacting with. Allowing you to block malware including those in files previously unseen. Helping you avoid zero day attacks.  SophosLabs Intelix passes each submitted file through an array of granular threat detection analyzers composed  of threat deterministic and machine learning models to derive a threat verdict and an intelligence report. Examples of analysis include:  File genetic similarity intersection machine learning analysis, suspicious file attributes machine learning identification, Deep Anti-Virus scanning, industry detection coverage, and a lot more.  The results are available in JSON format, for easy parsing with any programming language, as well as a visually appealing HTML report, ideal for human reading.  You can read more about [SophosLabs Intelix APIs here](/doc/index.html).  #### Billing  You are billed for getting a report. This might happen in the following ways:  * You request a report by file hash. You are billed if SophosLabs can provide you a report. * You submit a file for analysis. You are billed for the submission (pre-paying for the report). You get a job id for the submission.  NOTE: Requests for a report by job id are not billed when the report is provided, as you have already paid at file submit. 
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SophosLabs.Intellix.Client.SwaggerDateConverter;

namespace SophosLabs.Intellix.Model
{
    /// <summary>
    /// This section shows the overall score for each file analysis, each ranging from 0 (benign) to 100 (malicious).    * genetic_analysis: The genetic_analysis overall score is the (calibrated) score from the PE features trained random forest model.   * feature_maliciousness: The feature_maliciousness score is the (calibrated) score from the Manalyze feature trained random forest model.   * feature_intersections: The feature_intersections score is the score from the trained random forest model.   * black_box: The black_box overall score is identical to the score in ml_file.analyses.black_box.benign.  **example:** {\&quot;feature_maliciousness\&quot;: 0.0004236161539166211, \&quot;genetic_analysis\&quot;: 0.0986164718054265, \&quot;black_box\&quot;: 0.0986164718054265} 
    /// </summary>
    [DataContract]
        public partial class ReportMlFileOverallScores :  IEquatable<ReportMlFileOverallScores>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportMlFileOverallScores" /> class.
        /// </summary>
        /// <param name="blackBox">blackBox.</param>
        /// <param name="featureMaliciousness">featureMaliciousness.</param>
        /// <param name="geneticAnalysis">geneticAnalysis.</param>
        public ReportMlFileOverallScores(decimal? blackBox = default(decimal?), decimal? featureMaliciousness = default(decimal?), decimal? geneticAnalysis = default(decimal?))
        {
            this.BlackBox = blackBox;
            this.FeatureMaliciousness = featureMaliciousness;
            this.GeneticAnalysis = geneticAnalysis;
        }
        
        /// <summary>
        /// Gets or Sets BlackBox
        /// </summary>
        [DataMember(Name="black_box", EmitDefaultValue=false)]
        public decimal? BlackBox { get; set; }

        /// <summary>
        /// Gets or Sets FeatureMaliciousness
        /// </summary>
        [DataMember(Name="feature_maliciousness", EmitDefaultValue=false)]
        public decimal? FeatureMaliciousness { get; set; }

        /// <summary>
        /// Gets or Sets GeneticAnalysis
        /// </summary>
        [DataMember(Name="genetic_analysis", EmitDefaultValue=false)]
        public decimal? GeneticAnalysis { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReportMlFileOverallScores {\n");
            sb.Append("  BlackBox: ").Append(BlackBox).Append("\n");
            sb.Append("  FeatureMaliciousness: ").Append(FeatureMaliciousness).Append("\n");
            sb.Append("  GeneticAnalysis: ").Append(GeneticAnalysis).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReportMlFileOverallScores);
        }

        /// <summary>
        /// Returns true if ReportMlFileOverallScores instances are equal
        /// </summary>
        /// <param name="input">Instance of ReportMlFileOverallScores to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReportMlFileOverallScores input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BlackBox == input.BlackBox ||
                    (this.BlackBox != null &&
                    this.BlackBox.Equals(input.BlackBox))
                ) && 
                (
                    this.FeatureMaliciousness == input.FeatureMaliciousness ||
                    (this.FeatureMaliciousness != null &&
                    this.FeatureMaliciousness.Equals(input.FeatureMaliciousness))
                ) && 
                (
                    this.GeneticAnalysis == input.GeneticAnalysis ||
                    (this.GeneticAnalysis != null &&
                    this.GeneticAnalysis.Equals(input.GeneticAnalysis))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BlackBox != null)
                    hashCode = hashCode * 59 + this.BlackBox.GetHashCode();
                if (this.FeatureMaliciousness != null)
                    hashCode = hashCode * 59 + this.FeatureMaliciousness.GetHashCode();
                if (this.GeneticAnalysis != null)
                    hashCode = hashCode * 59 + this.GeneticAnalysis.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
