/* 
 * Static File Analysis API
 *
 * Use this easy service to understand the characteristics of the file your application or service is interacting with. Allowing you to block malware including those in files previously unseen. Helping you avoid zero day attacks.  SophosLabs Intelix passes each submitted file through an array of granular threat detection analyzers composed  of threat deterministic and machine learning models to derive a threat verdict and an intelligence report. Examples of analysis include:  File genetic similarity intersection machine learning analysis, suspicious file attributes machine learning identification, Deep Anti-Virus scanning, industry detection coverage, and a lot more.  The results are available in JSON format, for easy parsing with any programming language, as well as a visually appealing HTML report, ideal for human reading.  You can read more about [SophosLabs Intelix APIs here](/doc/index.html).  #### Billing  You are billed for getting a report. This might happen in the following ways:  * You request a report by file hash. You are billed if SophosLabs can provide you a report. * You submit a file for analysis. You are billed for the submission (pre-paying for the report). You get a job id for the submission.  NOTE: Requests for a report by job id are not billed when the report is provided, as you have already paid at file submit. 
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SophosLabs.Intellix.Client.SwaggerDateConverter;

namespace SophosLabs.Intellix.Model
{
    /// <summary>
    /// Scores relating to how malicious the file was found to be. Specifically, there are two scores: &#x27;raw&#x27; (the raw model score output), and &#x27;score&#x27; (the calibrated output). &#x27;score&#x27; is more useful. A higher score means more malicious; a lower score means more benignCurrently, a score of e.g. 30 corresponds to a false-positive rate of 10e-3, a score of 20 corresponds to a false-positive rate of 10e-2, etc. **example:** {\&quot;score\&quot;: 3, \&quot;raw\&quot;: 8.47574369799986e-07} 
    /// </summary>
    [DataContract]
        public partial class ReportMlFileAnalysesBlackBoxBenign :  IEquatable<ReportMlFileAnalysesBlackBoxBenign>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportMlFileAnalysesBlackBoxBenign" /> class.
        /// </summary>
        /// <param name="raw">raw (required).</param>
        /// <param name="score">score (required).</param>
        public ReportMlFileAnalysesBlackBoxBenign(decimal? raw = default(decimal?), int? score = default(int?))
        {
            // to ensure "raw" is required (not null)
            if (raw == null)
            {
                throw new InvalidDataException("raw is a required property for ReportMlFileAnalysesBlackBoxBenign and cannot be null");
            }
            else
            {
                this.Raw = raw;
            }
            // to ensure "score" is required (not null)
            if (score == null)
            {
                throw new InvalidDataException("score is a required property for ReportMlFileAnalysesBlackBoxBenign and cannot be null");
            }
            else
            {
                this.Score = score;
            }
        }
        
        /// <summary>
        /// Gets or Sets Raw
        /// </summary>
        [DataMember(Name="raw", EmitDefaultValue=false)]
        public decimal? Raw { get; set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        [DataMember(Name="score", EmitDefaultValue=false)]
        public int? Score { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReportMlFileAnalysesBlackBoxBenign {\n");
            sb.Append("  Raw: ").Append(Raw).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReportMlFileAnalysesBlackBoxBenign);
        }

        /// <summary>
        /// Returns true if ReportMlFileAnalysesBlackBoxBenign instances are equal
        /// </summary>
        /// <param name="input">Instance of ReportMlFileAnalysesBlackBoxBenign to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReportMlFileAnalysesBlackBoxBenign input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Raw == input.Raw ||
                    (this.Raw != null &&
                    this.Raw.Equals(input.Raw))
                ) && 
                (
                    this.Score == input.Score ||
                    (this.Score != null &&
                    this.Score.Equals(input.Score))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Raw != null)
                    hashCode = hashCode * 59 + this.Raw.GetHashCode();
                if (this.Score != null)
                    hashCode = hashCode * 59 + this.Score.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
