/* 
 * Static File Analysis API
 *
 * Use this easy service to understand the characteristics of the file your application or service is interacting with. Allowing you to block malware including those in files previously unseen. Helping you avoid zero day attacks.  SophosLabs Intelix passes each submitted file through an array of granular threat detection analyzers composed  of threat deterministic and machine learning models to derive a threat verdict and an intelligence report. Examples of analysis include:  File genetic similarity intersection machine learning analysis, suspicious file attributes machine learning identification, Deep Anti-Virus scanning, industry detection coverage, and a lot more.  The results are available in JSON format, for easy parsing with any programming language, as well as a visually appealing HTML report, ideal for human reading.  You can read more about [SophosLabs Intelix APIs here](/doc/index.html).  #### Billing  You are billed for getting a report. This might happen in the following ways:  * You request a report by file hash. You are billed if SophosLabs can provide you a report. * You submit a file for analysis. You are billed for the submission (pre-paying for the report). You get a job id for the submission.  NOTE: Requests for a report by job id are not billed when the report is provided, as you have already paid at file submit. 
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SophosLabs.Intellix.Client.SwaggerDateConverter;

namespace SophosLabs.Intellix.Model
{
    /// <summary>
    /// ReportPeAnalysisSections
    /// </summary>
    [DataContract]
        public partial class ReportPeAnalysisSections :  IEquatable<ReportPeAnalysisSections>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportPeAnalysisSections" /> class.
        /// </summary>
        /// <param name="characteristics">characteristics (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="number">number (required).</param>
        /// <param name="physicaladdress">physicaladdress (required).</param>
        /// <param name="sizeofrawdata">sizeofrawdata (required).</param>
        /// <param name="virtualaddress">virtualaddress (required).</param>
        /// <param name="virtualsize">virtualsize (required).</param>
        public ReportPeAnalysisSections(List<string> characteristics = default(List<string>), string name = default(string), int? number = default(int?), int? physicaladdress = default(int?), int? sizeofrawdata = default(int?), int? virtualaddress = default(int?), int? virtualsize = default(int?))
        {
            // to ensure "characteristics" is required (not null)
            if (characteristics == null)
            {
                throw new InvalidDataException("characteristics is a required property for ReportPeAnalysisSections and cannot be null");
            }
            else
            {
                this.Characteristics = characteristics;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for ReportPeAnalysisSections and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "number" is required (not null)
            if (number == null)
            {
                throw new InvalidDataException("number is a required property for ReportPeAnalysisSections and cannot be null");
            }
            else
            {
                this.Number = number;
            }
            // to ensure "physicaladdress" is required (not null)
            if (physicaladdress == null)
            {
                throw new InvalidDataException("physicaladdress is a required property for ReportPeAnalysisSections and cannot be null");
            }
            else
            {
                this.Physicaladdress = physicaladdress;
            }
            // to ensure "sizeofrawdata" is required (not null)
            if (sizeofrawdata == null)
            {
                throw new InvalidDataException("sizeofrawdata is a required property for ReportPeAnalysisSections and cannot be null");
            }
            else
            {
                this.Sizeofrawdata = sizeofrawdata;
            }
            // to ensure "virtualaddress" is required (not null)
            if (virtualaddress == null)
            {
                throw new InvalidDataException("virtualaddress is a required property for ReportPeAnalysisSections and cannot be null");
            }
            else
            {
                this.Virtualaddress = virtualaddress;
            }
            // to ensure "virtualsize" is required (not null)
            if (virtualsize == null)
            {
                throw new InvalidDataException("virtualsize is a required property for ReportPeAnalysisSections and cannot be null");
            }
            else
            {
                this.Virtualsize = virtualsize;
            }
        }
        
        /// <summary>
        /// Gets or Sets Characteristics
        /// </summary>
        [DataMember(Name="characteristics", EmitDefaultValue=false)]
        public List<string> Characteristics { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name="number", EmitDefaultValue=false)]
        public int? Number { get; set; }

        /// <summary>
        /// Gets or Sets Physicaladdress
        /// </summary>
        [DataMember(Name="physicaladdress", EmitDefaultValue=false)]
        public int? Physicaladdress { get; set; }

        /// <summary>
        /// Gets or Sets Sizeofrawdata
        /// </summary>
        [DataMember(Name="sizeofrawdata", EmitDefaultValue=false)]
        public int? Sizeofrawdata { get; set; }

        /// <summary>
        /// Gets or Sets Virtualaddress
        /// </summary>
        [DataMember(Name="virtualaddress", EmitDefaultValue=false)]
        public int? Virtualaddress { get; set; }

        /// <summary>
        /// Gets or Sets Virtualsize
        /// </summary>
        [DataMember(Name="virtualsize", EmitDefaultValue=false)]
        public int? Virtualsize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReportPeAnalysisSections {\n");
            sb.Append("  Characteristics: ").Append(Characteristics).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Physicaladdress: ").Append(Physicaladdress).Append("\n");
            sb.Append("  Sizeofrawdata: ").Append(Sizeofrawdata).Append("\n");
            sb.Append("  Virtualaddress: ").Append(Virtualaddress).Append("\n");
            sb.Append("  Virtualsize: ").Append(Virtualsize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReportPeAnalysisSections);
        }

        /// <summary>
        /// Returns true if ReportPeAnalysisSections instances are equal
        /// </summary>
        /// <param name="input">Instance of ReportPeAnalysisSections to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReportPeAnalysisSections input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Characteristics == input.Characteristics ||
                    this.Characteristics != null &&
                    input.Characteristics != null &&
                    this.Characteristics.SequenceEqual(input.Characteristics)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.Physicaladdress == input.Physicaladdress ||
                    (this.Physicaladdress != null &&
                    this.Physicaladdress.Equals(input.Physicaladdress))
                ) && 
                (
                    this.Sizeofrawdata == input.Sizeofrawdata ||
                    (this.Sizeofrawdata != null &&
                    this.Sizeofrawdata.Equals(input.Sizeofrawdata))
                ) && 
                (
                    this.Virtualaddress == input.Virtualaddress ||
                    (this.Virtualaddress != null &&
                    this.Virtualaddress.Equals(input.Virtualaddress))
                ) && 
                (
                    this.Virtualsize == input.Virtualsize ||
                    (this.Virtualsize != null &&
                    this.Virtualsize.Equals(input.Virtualsize))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Characteristics != null)
                    hashCode = hashCode * 59 + this.Characteristics.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Number != null)
                    hashCode = hashCode * 59 + this.Number.GetHashCode();
                if (this.Physicaladdress != null)
                    hashCode = hashCode * 59 + this.Physicaladdress.GetHashCode();
                if (this.Sizeofrawdata != null)
                    hashCode = hashCode * 59 + this.Sizeofrawdata.GetHashCode();
                if (this.Virtualaddress != null)
                    hashCode = hashCode * 59 + this.Virtualaddress.GetHashCode();
                if (this.Virtualsize != null)
                    hashCode = hashCode * 59 + this.Virtualsize.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
