/* 
 * Static File Analysis API
 *
 * Use this easy service to understand the characteristics of the file your application or service is interacting with. Allowing you to block malware including those in files previously unseen. Helping you avoid zero day attacks.  SophosLabs Intelix passes each submitted file through an array of granular threat detection analyzers composed  of threat deterministic and machine learning models to derive a threat verdict and an intelligence report. Examples of analysis include:  File genetic similarity intersection machine learning analysis, suspicious file attributes machine learning identification, Deep Anti-Virus scanning, industry detection coverage, and a lot more.  The results are available in JSON format, for easy parsing with any programming language, as well as a visually appealing HTML report, ideal for human reading.  You can read more about [SophosLabs Intelix APIs here](/doc/index.html).  #### Billing  You are billed for getting a report. This might happen in the following ways:  * You request a report by file hash. You are billed if SophosLabs can provide you a report. * You submit a file for analysis. You are billed for the submission (pre-paying for the report). You get a job id for the submission.  NOTE: Requests for a report by job id are not billed when the report is provided, as you have already paid at file submit. 
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SophosLabs.Intellix.Client.SwaggerDateConverter;

namespace SophosLabs.Intellix.Model
{
    /// <summary>
    /// ReportPeAnalysisDigisigSigner
    /// </summary>
    [DataContract]
        public partial class ReportPeAnalysisDigisigSigner :  IEquatable<ReportPeAnalysisDigisigSigner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportPeAnalysisDigisigSigner" /> class.
        /// </summary>
        /// <param name="algorithm">algorithm (required).</param>
        /// <param name="certdepth">certdepth (required).</param>
        /// <param name="cn">cn (required).</param>
        /// <param name="issuer">issuer (required).</param>
        /// <param name="serial">serial (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="thumbprint">thumbprint (required).</param>
        /// <param name="usage">usage (required).</param>
        /// <param name="validFrom">validFrom (required).</param>
        /// <param name="validTo">validTo (required).</param>
        public ReportPeAnalysisDigisigSigner(string algorithm = default(string), int? certdepth = default(int?), string cn = default(string), string issuer = default(string), string serial = default(string), string status = default(string), string thumbprint = default(string), string usage = default(string), DateTime? validFrom = default(DateTime?), DateTime? validTo = default(DateTime?))
        {
            // to ensure "algorithm" is required (not null)
            if (algorithm == null)
            {
                throw new InvalidDataException("algorithm is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Algorithm = algorithm;
            }
            // to ensure "certdepth" is required (not null)
            if (certdepth == null)
            {
                throw new InvalidDataException("certdepth is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Certdepth = certdepth;
            }
            // to ensure "cn" is required (not null)
            if (cn == null)
            {
                throw new InvalidDataException("cn is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Cn = cn;
            }
            // to ensure "issuer" is required (not null)
            if (issuer == null)
            {
                throw new InvalidDataException("issuer is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Issuer = issuer;
            }
            // to ensure "serial" is required (not null)
            if (serial == null)
            {
                throw new InvalidDataException("serial is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Serial = serial;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "thumbprint" is required (not null)
            if (thumbprint == null)
            {
                throw new InvalidDataException("thumbprint is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Thumbprint = thumbprint;
            }
            // to ensure "usage" is required (not null)
            if (usage == null)
            {
                throw new InvalidDataException("usage is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.Usage = usage;
            }
            // to ensure "validFrom" is required (not null)
            if (validFrom == null)
            {
                throw new InvalidDataException("validFrom is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.ValidFrom = validFrom;
            }
            // to ensure "validTo" is required (not null)
            if (validTo == null)
            {
                throw new InvalidDataException("validTo is a required property for ReportPeAnalysisDigisigSigner and cannot be null");
            }
            else
            {
                this.ValidTo = validTo;
            }
        }
        
        /// <summary>
        /// Gets or Sets Algorithm
        /// </summary>
        [DataMember(Name="algorithm", EmitDefaultValue=false)]
        public string Algorithm { get; set; }

        /// <summary>
        /// Gets or Sets Certdepth
        /// </summary>
        [DataMember(Name="certdepth", EmitDefaultValue=false)]
        public int? Certdepth { get; set; }

        /// <summary>
        /// Gets or Sets Cn
        /// </summary>
        [DataMember(Name="cn", EmitDefaultValue=false)]
        public string Cn { get; set; }

        /// <summary>
        /// Gets or Sets Issuer
        /// </summary>
        [DataMember(Name="issuer", EmitDefaultValue=false)]
        public string Issuer { get; set; }

        /// <summary>
        /// Gets or Sets Serial
        /// </summary>
        [DataMember(Name="serial", EmitDefaultValue=false)]
        public string Serial { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Thumbprint
        /// </summary>
        [DataMember(Name="thumbprint", EmitDefaultValue=false)]
        public string Thumbprint { get; set; }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>
        [DataMember(Name="usage", EmitDefaultValue=false)]
        public string Usage { get; set; }

        /// <summary>
        /// Gets or Sets ValidFrom
        /// </summary>
        [DataMember(Name="valid_from", EmitDefaultValue=false)]
        public DateTime? ValidFrom { get; set; }

        /// <summary>
        /// Gets or Sets ValidTo
        /// </summary>
        [DataMember(Name="valid_to", EmitDefaultValue=false)]
        public DateTime? ValidTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReportPeAnalysisDigisigSigner {\n");
            sb.Append("  Algorithm: ").Append(Algorithm).Append("\n");
            sb.Append("  Certdepth: ").Append(Certdepth).Append("\n");
            sb.Append("  Cn: ").Append(Cn).Append("\n");
            sb.Append("  Issuer: ").Append(Issuer).Append("\n");
            sb.Append("  Serial: ").Append(Serial).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Thumbprint: ").Append(Thumbprint).Append("\n");
            sb.Append("  Usage: ").Append(Usage).Append("\n");
            sb.Append("  ValidFrom: ").Append(ValidFrom).Append("\n");
            sb.Append("  ValidTo: ").Append(ValidTo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReportPeAnalysisDigisigSigner);
        }

        /// <summary>
        /// Returns true if ReportPeAnalysisDigisigSigner instances are equal
        /// </summary>
        /// <param name="input">Instance of ReportPeAnalysisDigisigSigner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReportPeAnalysisDigisigSigner input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Algorithm == input.Algorithm ||
                    (this.Algorithm != null &&
                    this.Algorithm.Equals(input.Algorithm))
                ) && 
                (
                    this.Certdepth == input.Certdepth ||
                    (this.Certdepth != null &&
                    this.Certdepth.Equals(input.Certdepth))
                ) && 
                (
                    this.Cn == input.Cn ||
                    (this.Cn != null &&
                    this.Cn.Equals(input.Cn))
                ) && 
                (
                    this.Issuer == input.Issuer ||
                    (this.Issuer != null &&
                    this.Issuer.Equals(input.Issuer))
                ) && 
                (
                    this.Serial == input.Serial ||
                    (this.Serial != null &&
                    this.Serial.Equals(input.Serial))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Thumbprint == input.Thumbprint ||
                    (this.Thumbprint != null &&
                    this.Thumbprint.Equals(input.Thumbprint))
                ) && 
                (
                    this.Usage == input.Usage ||
                    (this.Usage != null &&
                    this.Usage.Equals(input.Usage))
                ) && 
                (
                    this.ValidFrom == input.ValidFrom ||
                    (this.ValidFrom != null &&
                    this.ValidFrom.Equals(input.ValidFrom))
                ) && 
                (
                    this.ValidTo == input.ValidTo ||
                    (this.ValidTo != null &&
                    this.ValidTo.Equals(input.ValidTo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Algorithm != null)
                    hashCode = hashCode * 59 + this.Algorithm.GetHashCode();
                if (this.Certdepth != null)
                    hashCode = hashCode * 59 + this.Certdepth.GetHashCode();
                if (this.Cn != null)
                    hashCode = hashCode * 59 + this.Cn.GetHashCode();
                if (this.Issuer != null)
                    hashCode = hashCode * 59 + this.Issuer.GetHashCode();
                if (this.Serial != null)
                    hashCode = hashCode * 59 + this.Serial.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Thumbprint != null)
                    hashCode = hashCode * 59 + this.Thumbprint.GetHashCode();
                if (this.Usage != null)
                    hashCode = hashCode * 59 + this.Usage.GetHashCode();
                if (this.ValidFrom != null)
                    hashCode = hashCode * 59 + this.ValidFrom.GetHashCode();
                if (this.ValidTo != null)
                    hashCode = hashCode * 59 + this.ValidTo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
