/* 
 * Static File Analysis API
 *
 * Use this easy service to understand the characteristics of the file your application or service is interacting with. Allowing you to block malware including those in files previously unseen. Helping you avoid zero day attacks.  SophosLabs Intelix passes each submitted file through an array of granular threat detection analyzers composed  of threat deterministic and machine learning models to derive a threat verdict and an intelligence report. Examples of analysis include:  File genetic similarity intersection machine learning analysis, suspicious file attributes machine learning identification, Deep Anti-Virus scanning, industry detection coverage, and a lot more.  The results are available in JSON format, for easy parsing with any programming language, as well as a visually appealing HTML report, ideal for human reading.  You can read more about [SophosLabs Intelix APIs here](/doc/index.html).  #### Billing  You are billed for getting a report. This might happen in the following ways:  * You request a report by file hash. You are billed if SophosLabs can provide you a report. * You submit a file for analysis. You are billed for the submission (pre-paying for the report). You get a job id for the submission.  NOTE: Requests for a report by job id are not billed when the report is provided, as you have already paid at file submit. 
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SophosLabs.Intellix.Api;
using SophosLabs.Intellix.Model;
using SophosLabs.Intellix.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SophosLabs.Intellix.Test
{
    /// <summary>
    ///  Class for testing ReportDocumentAnalysisMetaData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportDocumentAnalysisMetaDataTests
    {
        // TODO uncomment below to declare an instance variable for ReportDocumentAnalysisMetaData
        //private ReportDocumentAnalysisMetaData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportDocumentAnalysisMetaData
            //instance = new ReportDocumentAnalysisMetaData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportDocumentAnalysisMetaData
        /// </summary>
        [Test]
        public void ReportDocumentAnalysisMetaDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportDocumentAnalysisMetaData
            //Assert.IsInstanceOfType<ReportDocumentAnalysisMetaData> (instance, "variable 'instance' is a ReportDocumentAnalysisMetaData");
        }


        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Test]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Codepage'
        /// </summary>
        [Test]
        public void CodepageTest()
        {
            // TODO unit test for the property 'Codepage'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'ContentStatus'
        /// </summary>
        [Test]
        public void ContentStatusTest()
        {
            // TODO unit test for the property 'ContentStatus'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Test]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'CreatingApplication'
        /// </summary>
        [Test]
        public void CreatingApplicationTest()
        {
            // TODO unit test for the property 'CreatingApplication'
        }
        /// <summary>
        /// Test the property 'Digisig'
        /// </summary>
        [Test]
        public void DigisigTest()
        {
            // TODO unit test for the property 'Digisig'
        }
        /// <summary>
        /// Test the property 'Encryption'
        /// </summary>
        [Test]
        public void EncryptionTest()
        {
            // TODO unit test for the property 'Encryption'
        }
        /// <summary>
        /// Test the property 'HiddenSlides'
        /// </summary>
        [Test]
        public void HiddenSlidesTest()
        {
            // TODO unit test for the property 'HiddenSlides'
        }
        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Test]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'LastBackup'
        /// </summary>
        [Test]
        public void LastBackupTest()
        {
            // TODO unit test for the property 'LastBackup'
        }
        /// <summary>
        /// Test the property 'LastPrinted'
        /// </summary>
        [Test]
        public void LastPrintedTest()
        {
            // TODO unit test for the property 'LastPrinted'
        }
        /// <summary>
        /// Test the property 'LastSavedBy'
        /// </summary>
        [Test]
        public void LastSavedByTest()
        {
            // TODO unit test for the property 'LastSavedBy'
        }
        /// <summary>
        /// Test the property 'LastSavedTime'
        /// </summary>
        [Test]
        public void LastSavedTimeTest()
        {
            // TODO unit test for the property 'LastSavedTime'
        }
        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Test]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }
        /// <summary>
        /// Test the property 'LinkBase'
        /// </summary>
        [Test]
        public void LinkBaseTest()
        {
            // TODO unit test for the property 'LinkBase'
        }
        /// <summary>
        /// Test the property 'Manager'
        /// </summary>
        [Test]
        public void ManagerTest()
        {
            // TODO unit test for the property 'Manager'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'NumChars'
        /// </summary>
        [Test]
        public void NumCharsTest()
        {
            // TODO unit test for the property 'NumChars'
        }
        /// <summary>
        /// Test the property 'NumPages'
        /// </summary>
        [Test]
        public void NumPagesTest()
        {
            // TODO unit test for the property 'NumPages'
        }
        /// <summary>
        /// Test the property 'NumWords'
        /// </summary>
        [Test]
        public void NumWordsTest()
        {
            // TODO unit test for the property 'NumWords'
        }
        /// <summary>
        /// Test the property 'Paragraphs'
        /// </summary>
        [Test]
        public void ParagraphsTest()
        {
            // TODO unit test for the property 'Paragraphs'
        }
        /// <summary>
        /// Test the property 'PresentationTarget'
        /// </summary>
        [Test]
        public void PresentationTargetTest()
        {
            // TODO unit test for the property 'PresentationTarget'
        }
        /// <summary>
        /// Test the property 'RevisionNumber'
        /// </summary>
        [Test]
        public void RevisionNumberTest()
        {
            // TODO unit test for the property 'RevisionNumber'
        }
        /// <summary>
        /// Test the property 'SharedDoc'
        /// </summary>
        [Test]
        public void SharedDocTest()
        {
            // TODO unit test for the property 'SharedDoc'
        }
        /// <summary>
        /// Test the property 'Slides'
        /// </summary>
        [Test]
        public void SlidesTest()
        {
            // TODO unit test for the property 'Slides'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'TotalEditTime'
        /// </summary>
        [Test]
        public void TotalEditTimeTest()
        {
            // TODO unit test for the property 'TotalEditTime'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
